export const clubs    = "https://bde-api.cluster-ig3.igpolytech.fr/api/clubs/"
export const events   = "https://bde-api.cluster-ig3.igpolytech.fr/api/events/"
export const partners = "https://bde-api.cluster-ig3.igpolytech.fr/api/partners/"
export const promos   = "https://bde-api.cluster-ig3.igpolytech.fr/api/promos/"
export const users    = "https://bde-api.cluster-ig3.igpolytech.fr/api/users/"
export const roles    = "https://bde-api.cluster-ig3.igpolytech.fr/api/roles/"
export const signup   = "https://bde-api.cluster-ig3.igpolytech.fr/api/signup/"
export const signin   = "https://bde-api.cluster-ig3.igpolytech.fr/api/signin/"